### ISSUE TITLE
Orientation not preserved; gene names not showing

### ISSUE THREAD

**Issue by Laura-Alex** [cogitokat/genegraphics#6]
Hello! I have found Gene Graphics very useful in the past - thank you for making it.

I think that the move from https://katlabs.cc/genegraphics/ to https://www.genegraphics.net/ and https://v2.genegraphics.net/ led to a bug for me. Right now, the gene names are not showing as labels (I don't mind it that much), and, more importantly, the gene orientation is not preserved (all genes show as forward).

This did not happen previously. I have also tried to upload to the new sites some of my old .tsv files , which previously worked fine, but again, orientation is not preserved. If there is just a setting that I haven't figured out yet, please let me know! Much appreciated.

**Comment by katlabs** [comment]
Hi @Laura-Alex, thank you for opening an issue. Would you be able to provide a file that you're using that is not working for you? You can email it to me at katherinej.harrison@gmail.com, if you prefer. Also, can you let me know what browser you are using? If you provide these, I can look into it as soon as I am able to.

**Comment by Laura-Alex** [comment]
Sorry for the delay. (at the time, I just used Inkscape to reverse genes manually)

I have tried this in Firefox and Chrome. Neither works. A table such as the one below (pasted in Notepad and then with the extension changed to .tsv) simply results in an image with the orientation removed. Hope it helps.
```

Genome	Start	Stop	Strand	Gene Name	Function	Color
test	25722	26039	-	nifW		#8470ff
test	26036	26251	-	KFKJPILI_00249	hypothetical protein	gray
test	26348	26824	-	KFKJPILI_00250	hypothetical protein	gray
test	26821	27234	-	nifX	hypothetical protein	#8470ff
test	27347	28681	-	nifN	Nitrogenase molybdenum-iron protein beta chain	#8470ff
test	28681	30123	-	nifE	Nitrogenase molybdenum-iron protein alpha chain	#8470ff
test	30431	30757	-	KFKJPILI_00254	hypothetical protein	gray
test	31035	32573	-	nifK_6	Nitrogenase molybdenum-iron protein beta chain	#8470ff
test	32773	32904	-	nifD		#8470ff
test	33033	34451	+	KFKJPILI_00256	hypothetical protein	gray
test	34645	35667	+	KFKJPILI_00257	hypothetical protein	gray
test	35967	36527	+	KFKJPILI_00258	hypothetical protein	gray
test	36555	36872	-	KFKJPILI_00259	hypothetical protein	gray
test	36951	37121	-	KFKJPILI_00260	hypothetical protein	gray
test	37190	38020	+	KFKJPILI_00261	hypothetical protein	gray
test	38283	39437	+	KFKJPILI_00262	hypothetical protein	gray
test	39799	40377	+	KFKJPILI_00263	hypothetical protein	gray
test	40406	41785	+	KFKJPILI_00264	Putative cytochrome P450 137	gray
test	42276	42392	+	KFKJPILI_00265	hypothetical protein	gray
test	42944	43225	+	KFKJPILI_00266	hypothetical protein	gray
test	43252	43455	+	KFKJPILI_00267	hypothetical protein	gray
test	43482	43712	+	KFKJPILI_00268	hypothetical protein	gray
test	44113	45555	-	nifD_7	Nitrogenase molybdenum-iron protein alpha chain	#8470ff
test	45688	46575	-	nifH1_1	Nitrogenase iron protein 1	#8470ff
test	46793	47695	-	nifU	Fe/S biogenesis protein NfuA	#8470ff
test	47827	49029	-	nifS_3	Cysteine desulfurase NifS	#8470ff
test	49032	49088	-	fdxN		#8470ff
```

![Untitled](https://github.com/katlabs/genegraphics/assets/39491172/ccf5172a-013c-41c0-854d-c7af421ada40)

**Comment by katlabs** [comment]
I have pushed some updates to the tool that should resolve your issues. Let me know if there are still problems, if you get a chance to try it. If I don't hear from you in a couple of weeks, I will close this issue, but you are always welcome to open another one any time!
