### ISSUE TITLE
scale does not seem accurate

### ISSUE THREAD

**Issue by gdiazcruz** [cogitokat/genegraphics#7]
Hello,

I really like your tool. I am using gene clusters from a Streptomyces genome and the length of the scale is not very accurate. The 1kb scale is also too small when dealing with clusters (>50kb) and can't be changed or customized. 

Thanks

**Comment by katlabs** [comment]
Hello,
I have added an option to customize the size of the scale. Hopefully, this resolves your issue-- please let me know. If I don't hear from you in a couple of weeks, I will consider it resolved, but you are welcome to open another issue any time!

**Comment by gdiazcruz** [comment]
Hello!

Thanks, I just tried it out and it's much better. 5 and 10kb scales definitely improve the image.

Thanks again!
